//
// Created by 24547 on 2026/5/28.
//

#ifndef MULTIFUNCTIONAL_MONITOR_STATION_LIGHT_H
#define MULTIFUNCTIONAL_MONITOR_STATION_LIGHT_H

void Obtain_Light_Intensity(void);

#endif //MULTIFUNCTIONAL_MONITOR_STATION_LIGHT_H
